import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { Badge, Card, Icon } from "../../components/ui";

const toneFor = (risk) => risk === "High" ? "high" : risk === "Medium" ? "medium" : "low";

function AnalysisRequired() {
  return <main className="min-w-0" id="main-content"><Card className="mx-auto max-w-2xl p-7 text-center sm:p-9"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-brand-100 text-brand-800"><Icon name="shield" size={26} /></span><p className="mb-0 mt-4 text-xs font-bold uppercase tracking-wide text-brand-700">Analysis required</p><h1 className="mb-2 mt-1 text-2xl font-bold text-brand-900">Analyze the content before reporting</h1><p className="m-0 text-sm leading-6 text-muted">Reports are linked to an analysis result so the suspicious text or URL and its assessment can carry over accurately.</p><Link to="/analysis" className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-lg bg-brand-800 px-5 text-sm font-bold text-white hover:bg-brand-700"><Icon name="shield" size={17} />Analyze scam</Link></Card></main>;
}

export function ReportPage() {
  const { state } = useLocation();
  const navigate = useNavigate();
  const analysis = state?.analysis;
  const [context, setContext] = useState("");
  const [confirmed, setConfirmed] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  if (!analysis?.analysis || !analysis?.normalizedInput) return <AnalysisRequired />;
  if (submitted) return <main className="min-w-0" id="main-content"><Card className="mx-auto max-w-2xl p-7 text-center sm:p-9"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#eaf8f3] text-risk-low"><Icon name="check" size={28} /></span><p className="mb-0 mt-4 text-xs font-bold uppercase tracking-wide text-risk-low">Report prepared</p><h1 className="mb-2 mt-1 text-2xl font-bold text-brand-900">Thank you for looking out for the community</h1><p className="mx-auto mb-0 mt-2 max-w-lg text-sm leading-relaxed text-muted">This frontend prototype has not connected report submission to the backend yet. Your analyzed content has remained in this browser flow only.</p><div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/analysis" className="inline-flex min-h-11 items-center justify-center rounded-lg bg-brand-800 px-4 text-sm font-bold text-white">Analyze another item</Link><Link to="/" className="inline-flex min-h-11 items-center justify-center rounded-lg border border-line bg-white px-4 text-sm font-bold text-brand-800">Return to community feed</Link></div></Card></main>;

  return <main className="min-w-0" id="main-content"><div className="mb-5"><p className="m-0 text-xs font-bold uppercase tracking-[0.1em] text-brand-700">Step 4 · Report your encounter</p><h1 className="mb-1 mt-1 text-2xl font-bold text-brand-900">Add context to your report</h1><p className="m-0 max-w-2xl text-sm text-muted">The analyzed content and safety assessment have already been carried over. Tell us only what happened.</p></div>
    <Card className="mb-4 border-[#cbdcf0] bg-[#f8fbff] p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="m-0 text-xs font-bold uppercase tracking-wide text-brand-700">From your analysis</p><h2 className="mb-0 mt-1 text-base font-bold text-brand-900">{analysis.inputType === "URL" ? "Suspicious website URL" : "Suspicious text"}</h2></div><Badge tone={toneFor(analysis.risk)}>{analysis.risk} risk</Badge></div><p className="mb-0 mt-3 break-words rounded-lg bg-white p-3 font-mono text-xs leading-5 text-[#40546b]">{analysis.normalizedInput}</p><p className="mb-0 mt-3 text-sm leading-6 text-muted"><strong className="text-[#40546b]">Assessment:</strong> {analysis.analysis.summary}</p></Card>
    <Card className="overflow-hidden"><form className="grid gap-5 p-5 sm:p-6" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><label className="grid gap-1.5 text-sm font-bold text-ink">What happened?<textarea required rows="6" value={context} onChange={(event) => setContext(event.target.value)} className="resize-y rounded-lg border border-line p-3 text-base font-normal outline-none placeholder:text-[#8a97a8] focus:border-brand-700 focus:ring-2 focus:ring-[#d9ebfa]" placeholder="For example: I received this message after an order, and the sender asked me to pay a fee." /></label><p className="-mt-3 mb-0 text-xs leading-5 text-muted">Do not include passwords, OTP codes, banking details, or other private information.</p><div className="rounded-xl border border-line bg-[#fbfcfe] p-4"><h2 className="m-0 text-sm font-bold text-brand-900">Included with this report</h2><ul className="mb-0 mt-2 grid gap-1 pl-5 text-sm leading-6 text-muted"><li>Analyzed text or URL</li><li>{analysis.risk} assessment and detected indicators</li><li>{analysis.matchedScamCases?.length || 0} similar scam case reference{analysis.matchedScamCases?.length === 1 ? "" : "s"}</li></ul></div><label className="flex items-start gap-3 text-sm leading-6 text-muted"><input required type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} className="mt-1 h-4 w-4 accent-[#0c4698]" /><span>I confirm this report is honest and does not expose private information.</span></label><div className="flex flex-col-reverse gap-3 border-t border-line pt-5 sm:flex-row sm:items-center sm:justify-between"><button type="button" onClick={() => navigate("/analysis")} className="inline-flex min-h-11 items-center justify-center px-3 text-sm font-bold text-muted hover:text-brand-800">Back to analysis</button><button type="submit" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg border-0 bg-brand-800 px-5 text-sm font-bold text-white hover:bg-brand-700"><Icon name="edit" size={17} />Submit for review</button></div></form></Card>
  </main>;
}
