import {
  FiAlertTriangle,
  FiAward,
  FiBarChart2,
  FiBell,
  FiBriefcase,
  FiBookmark,
  FiBookOpen,
  FiChevronRight,
  FiChevronDown,
  FiCheckCircle,
  FiClock,
  FiEdit3,
  FiGlobe,
  FiGift,
  FiHeart,
  FiHelpCircle,
  FiHome,
  FiImage,
  FiLink,
  FiLogOut,
  FiMessageCircle,
  FiMoreHorizontal,
  FiPlus,
  FiSearch,
  FiSettings,
  FiShare2,
  FiShield,
  FiShoppingBag,
  FiTrendingUp,
  FiUsers,
  FiUploadCloud,
} from 'react-icons/fi'

const icons = {
  alert: FiAlertTriangle,
  bell: FiBell,
  briefcase: FiBriefcase,
  book: FiBookOpen,
  bookmark: FiBookmark,
  chart: FiBarChart2,
  chevron: FiChevronRight,
  chevronDown: FiChevronDown,
  check: FiCheckCircle,
  clock: FiClock,
  edit: FiEdit3,
  heart: FiHeart,
  help: FiHelpCircle,
  home: FiHome,
  globe: FiGlobe,
  gift: FiGift,
  image: FiImage,
  link: FiLink,
  logout: FiLogOut,
  message: FiMessageCircle,
  more: FiMoreHorizontal,
  plus: FiPlus,
  search: FiSearch,
  settings: FiSettings,
  share: FiShare2,
  shield: FiShield,
  shopping: FiShoppingBag,
  trendingUp: FiTrendingUp,
  trophy: FiAward,
  users: FiUsers,
  upload: FiUploadCloud,
}

export function Icon({ name, size = 18, className }) {
  const ReactIcon = icons[name]

  return ReactIcon ? <ReactIcon aria-hidden="true" size={size} className={className} /> : null
}
